### ISSUE TITLE
Rename `create` to `compile`

### ISSUE THREAD

**Issue by nevir** [convoyinc/dapper#13]
In its current incarnation, Dapper's API looks deceptively similar to RN's `StyleSheet`.  However, RN's `StyleSheet.create` gives you style values that you can immediately reference, whereas Dapper's only returns an intermediate representation (that must be passed to `compute`).

I think if we rename it to `compile`, we will avoid some confusion around that

**Comment by RylanH** [comment]
Solved in https://github.com/convoyinc/dapper/pull/21
